# Generated by Django 4.0.4 on 2022-04-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwspaper.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwspaper.post', verbose_name='Пост в категории'),
        ),
    ]
